import { SuiteModule } from '../types';

// Concierge suite modules (post-login only).
// IDs are stable because we use them as document keys in Firestore.
export const SUITE_MODULES: SuiteModule[] = [
  {
    id: 'intake',
    index: '01',
    title: 'Start Here',
    subtitle: 'A short concierge conversation to calibrate your suite.',
    kind: 'flow',
    relatedIds: ['episodes', 'brief', 'profile', 'ai_profile', 'gaps', 'plan'],
  },
  {
    id: 'episodes',
    index: '02',
    title: 'Episodes',
    subtitle: 'A bingeable feed of micro-dramas that upgrades your instincts.',
    kind: 'feed',
    relatedIds: ['brief', 'plan', 'assets'],
  },
  {
    id: 'brief',
    index: '03',
    title: 'The Brief',
    subtitle: 'What I learned, what matters most, and your next 72 hours.',
    kind: 'artifact',
    relatedIds: ['suite_distilled', 'plan', 'profile', 'ai_profile', 'gaps'],
  },
  {
    id: 'suite_distilled',
    index: '04',
    title: 'Your Suite, Distilled',
    subtitle: 'Two-column strategic map: what I learned and what needs to happen.',
    kind: 'artifact',
    relatedIds: ['brief', 'plan', 'readiness'],
  },
  {
    id: 'profile',
    index: '05',
    title: 'Your Profile',
    subtitle: 'Professional DNA: strengths, patterns, and leverage points.',
    kind: 'artifact',
    relatedIds: ['gaps', 'readiness', 'plan'],
  },
  {
    id: 'ai_profile',
    index: '06',
    title: 'Your AI Profile',
    subtitle: 'How you should use AI, based on how you work and decide.',
    kind: 'artifact',
    relatedIds: ['plan', 'gaps', 'readiness'],
  },
  {
    id: 'gaps',
    index: '07',
    title: 'Your Gaps',
    subtitle: 'What’s missing, what’s noisy, and what to tighten first.',
    kind: 'artifact',
    relatedIds: ['plan', 'readiness'],
  },
  {
    id: 'readiness',
    index: '08',
    title: 'AI Readiness',
    subtitle: 'Executive readiness report and curriculum tier routing.',
    kind: 'artifact',
    relatedIds: ['plan', 'cjs_execution'],
  },
  {
    id: 'cjs_execution',
    index: '09',
    title: 'ConciergeJobSearch',
    subtitle: 'Execution rail: resume, strategy, apply, interview, negotiation.',
    kind: 'artifact',
    relatedIds: ['plan', 'assets'],
  },
  {
    id: 'plan',
    index: '10',
    title: 'Your Plan',
    subtitle: '72 hours of momentum, then a 2-week sprint.',
    kind: 'artifact',
    relatedIds: ['assets', 'cjs_execution'],
  },
  {
    id: 'assets',
    index: '11',
    title: 'Your Assets',
    subtitle: 'Resume versions, outreach drafts, scripts, and links.',
    kind: 'collection',
    relatedIds: ['plan'],
  },
];
