import { CuratedMediaItem } from '../types';

export const STARTER_MEDIA_LIBRARY_PACK: CuratedMediaItem[] = [
  {
    id: 'starter-global-systems-pulse',
    enabled: true,
    title: 'Global Systems Pulse',
    subtitle: 'Reusable abstract motion bed for LLM metaphors, systems framing, and cross-industry AI narrative beats.',
    source_url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    source_kind: 'single',
    platform: 'direct',
    thumbnail_url: '',
    tags: ['editorial_grid', 'llm_metaphor', 'systems_animation', 'abstract_system', 'cross_industry', 'story'],
    priority: 10,
    surfaces: ['episodes'],
    rule: {
      audience: 'all',
      intents: [],
      focuses: ['skills', 'leadership'],
      paces: ['standard', 'story'],
      required_module_unlocks: ['episodes'],
    },
  },
  {
    id: 'starter-executive-signal-desk',
    enabled: true,
    title: 'Executive Signal Desk',
    subtitle: 'Cold-open footage for promotion, leadership, and internal-operator stakes.',
    source_url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    source_kind: 'single',
    platform: 'direct',
    thumbnail_url: '',
    tags: ['operator_console', 'cold_open', 'prestige_office', 'leadership', 'current_role', 'target_role'],
    priority: 20,
    surfaces: ['episodes'],
    rule: {
      audience: 'all',
      intents: ['current_role', 'target_role'],
      focuses: ['leadership', 'job_search'],
      paces: ['standard', 'story'],
      required_module_unlocks: ['episodes'],
    },
  },
  {
    id: 'starter-rehearsal-loop',
    enabled: true,
    title: 'Rehearsal Loop',
    subtitle: 'Reusable challenge/rehearsal sequence for execution coaching, role-play, and confidence drills.',
    source_url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    source_kind: 'single',
    platform: 'direct',
    thumbnail_url: '',
    tags: ['challenge_overlay', 'execution_rehearsal', 'process_automation_workflow', 'skills', 'story'],
    priority: 30,
    surfaces: ['episodes'],
    rule: {
      audience: 'all',
      intents: [],
      focuses: ['skills', 'job_search'],
      paces: ['straight', 'standard', 'story'],
      required_module_unlocks: ['episodes'],
    },
  },
  {
    id: 'starter-pattern-hunt',
    enabled: true,
    title: 'Pattern Hunt',
    subtitle: 'Direction-seeking visual route for exploration journeys, audits, and systems-discovery episodes.',
    source_url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    source_kind: 'single',
    platform: 'direct',
    thumbnail_url: '',
    tags: ['pattern_hunt', 'operator_console', 'cross_industry', 'not_sure', 'process_automation_workflow', 'story'],
    priority: 40,
    surfaces: ['episodes'],
    rule: {
      audience: 'all',
      intents: ['not_sure'],
      focuses: ['skills', 'leadership'],
      paces: ['standard', 'story'],
      required_module_unlocks: ['episodes'],
    },
  },
];
